version: '3.8'

services:
  soleane-massage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soleane-massage
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    
    # Health check pour monitoring
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.2'
    
    # Labels pour Traefik (si utilisé avec Coolify)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.soleane.rule=Host(`soleane-massage.yourdomain.com`)"
      - "traefik.http.routers.soleane.tls=true"
      - "traefik.http.routers.soleane.tls.certresolver=letsencrypt"
      - "traefik.http.services.soleane.loadbalancer.server.port=3002"

networks:
  default:
    external: true
    name: coolify